# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v2
      - name: Install depdencies
        run: |
          yum -y install gcc make perl
      - name: Install xz
        run: |
          curl -L -o xz-5.2.5.tar.gz https://sourceforge.net/projects/lzmautils/files/xz-5.2.5.tar.gz/download
          tar xfz xz-5.2.5.tar.gz
          cd xz-5.2.5
          ./configure CFLAGS=-fPIC LDFLAGS=-fPIC
          make
          make install
      - name: Install OpenSSL
        run: |
          curl -o openssl-1.1.1k.tar.gz https://www.openssl.org/source/openssl-1.1.1k.tar.gz
          tar xfz openssl-1.1.1k.tar.gz
          cd openssl-1.1.1k
          ./config LDFLAGS=-fPIC CFLAGS=-fPIC
          make
          make install
      - name: Install zlib
        run: |
          curl -o zlib-1.2.11.tar.gz https://zlib.net/zlib-1.2.11.tar.gz
          tar xfz zlib-1.2.11.tar.gz
          cd zlib-1.2.11
          ./configure
          make CFLAGS=-fPIC
          make install
      - name: install bzip2
        run: |
          curl -o bzip2-1.0.8.tar.gz https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
          tar xfz bzip2-1.0.8.tar.gz
          cd bzip2-1.0.8
          make CFLAGS=-fPIC
          make -f  Makefile-libbz2_so
          make install
          cp libbz2.so* /usr/local/lib/
      - name: install libarchive
        run: |
          curl -o libarchive-3.5.1.tar.gz https://libarchive.org/downloads/libarchive-3.5.1.tar.gz
          tar xfz libarchive-3.5.1.tar.gz
          cd libarchive-3.5.1
          ./configure --disable-static --disable-bsdtar --disable-bsdcpio --disable-bsdcat
          make LIBS="/usr/local/lib/liblzma.a /usr/local/lib64/libcrypto.a /usr/local/lib/libbz2.a /usr/local/lib/libz.a"
          LD_LIBRARY_PATH=/usr/local/lib ldd .libs/libarchive.so
      - name: Save libarchive
        uses: actions/upload-artifact@v2
        with:
          name: libarchive
          path: libarchive-3.5.1/.libs/
