# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v2
      - name: Install depdencies
        run: |
          yum -y install gcc make perl
      - name: Install xz
        run: |
          pwd
          curl -L -o xz-5.2.5.tar.gz https://sourceforge.net/projects/lzmautils/files/xz-5.2.5.tar.gz/download
          tar xfz xz-5.2.5.tar.gz
          cd xz-5.2.5
          ./configure CFLAGS=-fPIC LDFLAGS=-fPIC
          make
          make install
      - name: Install OpenSSL
        run: |
          pwd
          curl -o openssl-1.1.1k.tar.gz https://www.openssl.org/source/openssl-1.1.1k.tar.gz
          tar xfz openssl-1.1.1k.tar.gz
          openssl-1.1.1k/config
          make -C openssl-1.1.1k
          make -C openssl-1.1.1k install
      - name: Install zlib
        run: |
          pwd
          curl -o zlib-1.2.11.tar.gz https://zlib.net/zlib-1.2.11.tar.gz
          tar xfz zlib-1.2.11.tar.gz
      - name: install bzip2
        run: |
          pwd
          curl -o bzip2-1.0.8.tar.gz https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
          tar xfz bzip2-1.0.8.tar.gz
      - name: install libarchive
        run: |
          pwd
          curl -o libarchive-3.5.1.tar.gz https://libarchive.org/downloads/libarchive-3.5.1.tar.gz
          tar xfz libarchive-3.5.1.tar.gz
